feat: add ci variable to disable docker gateway build
adding the following HF_OffLine to make sure to not build AI Gateway

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -104,8 +104,15 @@ build-docker-model-gateway:
   extends:
     - .kaniko_base
   variables:
+    HF_OFFLINE: false
     KANIKO_BUILD_FILE: Dockerfile
     KANIKO_DESTINATION: "${TARGET_IMAGE}"
+  script:
+    - |
+      if [ "$HF_OFFLINE" = "true" ]; then
+        echo "HuggingFace Hub is down. Failing build-docker-model-gateway job."
+        exit 1
+      fi
 
 tests:unit:
   extends: .poetry
